### ISSUE TITLE
fid_eval.sh and fid_evaluation.py not Logging Properly

### ISSUE THREAD

**Issue by lchen64** [pantheon5100/pid_diffusion#1]
Hi, I checked and fid_eval.sh (fid_evaluation.py) seems to be logging to "model_zoo/pid_cifar/FID" every time, no matter what I set the OPENAI_LOGDIR environment variable to. This is a bit annoying because I want to log to the model_zoo folder in the root directory, and not to create one inside the scripts folder every time. Could you check on this when you have time? Thank You!

**Comment by pantheon5100** [comment]
Hi, the reason is that the code will manually set the OPENAI_LOGDIR environment variable (in the code fid_evaluation.py line 242). 

You can set the logging directory you want at the code fid_evaluation.py line 242 by setting a different path instead of str(exp_dir / "FID").

**Comment by lchen64** [comment]
Ah got it, thanks for your help!
