### ISSUE TITLE
Question about Numerical Differentiation v Automatic Differentiation Comparison (Figure 3) 

### ISSUE THREAD

**Issue by lchen64** [pantheon5100/pid_diffusion#3]
Hello,

If you get a chance, could you please clarify which numerical differentiation method was used for Figure 3 for the comparison between numerical and automatic differentiation? Is it the center difference (2nd order method), or just the 1st order method? It was shown that the 2nd order method achieves lower FID score, but in the Algorithm 1, 1st order method is specified for numerical differentiation in the PID training. 

Also if possible, could I double check whether 1st or 2nd order method was used for numerical differentiation for the other comparison figures, and in general, which was used for the model training? If Algorithm 1 was used, then it must have been 1st order, but I'm not sure they were all based on Alg1.

Thank you for your help!

**Comment by pantheon5100** [comment]
We use 1st order in general, except the comparison part.

**Comment by lchen64** [comment]
Thanks!

**Comment by lchen64** [comment]
Great, thanks!
