### ISSUE TITLE
DDP Training Only using the 1st Available GPU on Server Node

### ISSUE THREAD

**Issue by lchen64** [pantheon5100/pid_diffusion#4]
Sometimes, the distill_pid scripts only do the Physics Informed Distillation on the 1st available GPU for the server node (according to CUDA_VISIBLE_DEVICES). Do you have any idea why this might be, or have you had this problem before? I think it could have to do with the way DDP is being used.

**Comment by pantheon5100** [comment]
did you use "mpirun" to start the training?

**Comment by lchen64** [comment]
Yep, seems the problem still persists...

**Comment by pantheon5100** [comment]
Can you show me your running command line and did you change the dist_util
code.

Luke Chen ***@***.***>于2024年10月3日 周四下午2:03写道：

**Comment by pantheon5100** [comment]
There is a bug, you should delete cm/dist_util.py line 29. I have updated this change.
